#
# Template makefile for using the master
# Dazzle makefile.
#
include $(ToolsDir)/Makefile.os

target-post:
	@place $(O)/lib$(TARGET_NAME).a
	
# Post-buildstep to place files
include ../libc-includes.mk